version: '3.1'

services:
  spine1:
    container_name: spine1
    image: nicolaka/netshoot
    tty: true
    command: /bin/sh
    networks:
      - spine1-leaf1
      - spine1-leaf2

  spine2:
    container_name: spine2
    image: nicolaka/netshoot
    tty: true
    command: /bin/sh
    networks:
      - spine2-leaf1
      - spine2-leaf2

  leaf1:
    container_name: leaf1
    image: nicolaka/netshoot
    tty: true
    command: /bin/sh
    networks:
    networks:
      - spine1-leaf1
      - spine2-leaf1

  leaf2:
    container_name: leaf2
    image: nicolaka/netshoot
    tty: true
    command: /bin/sh
    networks:
      - spine1-leaf2
      - spine2-leaf2

networks:
  spine1-leaf1:
    driver_opts:
      com.docker.network.bridge.name: spine1-leaf1
  spine1-leaf2: {}
  spine2-leaf1: {}
  spine2-leaf2: {}
